### ISSUE TITLE
Fix graph svg elements centering

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/js_arules#23]
The graph visualization is not correctly plot, width and height are not set correctly and therefore the graph is on top left and title is also not well centred.

Check where it is produced and where probably the fix would be.

https://github.com/bacloud14/js_arules/commit/c990d4537d587cbe3729ce72d6174201cbba057d#r42996764

**Comment by sidneymiranda** [comment]
I would be happy to help.

**Comment by bacloud14** [comment]
Hooray, it's yours !

**Comment by bacloud14** [comment]
Hello ,
I was referring to the graph SVG elements. If you tried uploading the file in README you will understand the issue here. Nevertheless, I will check later for what you centered. It seems better if all elements in HTML are centered as well, I didn't thought if this so yeah, many thanks, we'll merge and approve later.

**Comment by bacloud14** [comment]
For the SVG graph, all work is in js d3 library you can see the pointed lines of code.

**Comment by sidneymiranda** [comment]
I understand, I don't have much experience with Axis, but I will try to help you.

**Comment by bacloud14** [comment]
me neither . 
If you want to give it a try, try digging the d3 API or some examples in the net, I started but couldn't. 
Good luck 🤞
