### ISSUE TITLE
Display tabular data from csv file when uploaded locally (selected)

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/js_arules#7]
.

**Comment by Stancobridge** [comment]
please explain better

**Comment by bacloud14** [comment]
Hi Stancobridge.
The goal is simple, when the user uploads a CSV file (always in client side with JS, this is why I said "select") the current page should show a review of the CSV file. There are few js libraries for this.

**Comment by bacloud14** [comment]
Resolved, many thanks !
